# TODO: create generator for this file for the end user
api:
  - .stacks/api/**/*

art:
  - .stacks/art/**/*

core:
  - .stacks/**/*

fonts:
  - .stacks/fonts/**/*

ide:
  - .stacks/ide/**/*

jetbrains:
  - .stacks/ide/jetbrains/**/*

vscode:
  - .stacks/ide/vscode/**/*

libs:
  - .stacks/libs/**/*

components:
  - .stacks/libs/components/**/*
  - resources/components/**/*

entries:
  - .stacks/libs/entries/**/*

examples:
  - .stacks/libs/examples/**/*

functions:
  - .stacks/libs/functions/**/*
  - resources/functions/**/*

scripts:
  - .stacks/scripts/**/*

stack:
  - .stacks/stacks/**/*

vcs:
  - .stacks/vcs/**/*

github:
  - .stacks/vcs/github/**/*

views:
  - .stacks/views/**/*
  - resources/views/**/*

web:
  - .stacks/views/web/**/*

actions:
  - .stacks/core/actions/**/*

ai:
  - .stacks/core/ai/**/*

alias:
  - .stacks/core/alias/**/*

analytics:
  - .stacks/core/analytics/**/*

arrays:
  - .stacks/core/arrays/**/*

auth:
  - .stacks/core/auth/**/*

buddy:
  - .stacks/core/buddy/**/*

build:
  - .stacks/core/build/**/*

cache:
  - .stacks/core/cache/**/*

chat:
  - .stacks/core/chat/**/*

cli:
  - .stacks/core/cli/**/*
  - app/commands/**/*

cloud:
  - .stacks/core/cloud/**/*

collections:
  - .stacks/core/collections/**/*

config:
  - .stacks/core/config/**/*
  - config/**/*

database:
  - .stacks/core/database/**/*

datetime:
  - .stacks/core/datetime/**/*

desktop:
  - .stacks/core/desktop/**/*
  - .stacks/views/desktop/**/*

development:
  - .stacks/core/development/**/*

dns:
  - .stacks/core/dns/**/*

docs:
  - .stacks/docs/**/*
  - .stacks/core/docs/**/*
  - resources/docs/**/*
  - config/docs.ts

email:
  - .stacks/core/email/**/*

error-handling:
  - .stacks/core/error-handling/**/*

events:
  - .stacks/core/events/**/*
  - app/events/**/*

faker:
  - .stacks/core/faker/**/*

git:
  - .stacks/core/git/**/*

health:
  - .stacks/core/health/**/*

lint:
  - .stacks/core/lint/**/*

logging:
  - .stacks/core/logging/**/*

modules:
  - .stacks/core/modules/**/*

notifications:
  - .stacks/core/notifications/**/*
  - app/notifications/**/*

objects:
  - .stacks/core/objects/**/*

orm:
  - .stacks/core/orm/**/*

pages:
  - .stacks/core/pages/**/*

path:
  - .stacks/core/path/**/*

payments:
  - .stacks/core/payments/**/*

push:
  - .stacks/core/push/**/*

query-builder:
  - .stacks/core/query-builder/**/*

queue:
  - .stacks/core/queue/**/*

real-time:
  - .stacks/core/real-time/**/*

router:
  - .stacks/core/router/**/*

scheduler:
  - .stacks/core/scheduler/**/*

search-engine:
  - .stacks/core/search-engine/**/*

security:
  - .stacks/core/security/**/*

server:
  - .stacks/core/server/**/*

signals:
  - .stacks/core/signals/**/*

slug:
  - .stacks/core/slug/**/*

sms:
  - .stacks/core/sms/**/*

storage:
  - .stacks/core/storage/**/*
  - storage/**/*

strings:
  - .stacks/core/strings/**/*

testing:
  - .stacks/core/testing/**/*

tinker:
  - .stacks/core/tinker/**/*

types:
  - .stacks/core/types/**/*

ui:
  - .stacks/core/ui/**/*

utils:
  - .stacks/core/utils/**/*

validation:
  - .stacks/core/validation/**/*

app:
  - app/**/*

jobs:
  - app/jobs/**/*

models:
  - app/models/**/*

resources:
  - resources/**/*

lang:
  - resources/lang/**/*

stores:
  - resources/stores/**/*

routes:
  - routes/**/*

tests:
  - tests/**/*
