packages:
  - ./.stacks/api
  - ./.stacks/core/*
  - ./.stacks/docs
  - ./.stacks/fonts/*
  - ./.stacks/ide/*
  - ./.stacks/libs/*
  - ./.stacks/stacks/*
  - ./.stacks/vcs/*
  - ./.stacks/views/*
  - ./.stacks
  - ./
