packages:
  - ./.stacks/api
  - ./.stacks/components/*
  - ./.stacks/config
  - ./.stacks/core/*
  - ./.stacks/docs
  - ./.stacks/fonts/*
  - ./.stacks/functions
  - ./.stacks/pages/*
  - ./.stacks/vscode
  - ./.stacks
  - ./
