packages:
  - ./.stacks/buddy
  - ./.stacks/core/*
  - ./.stacks/components/*
  - ./.stacks/docs
  - ./.stacks/fonts/*
  - ./.stacks/functions
  - ./.stacks/desktop
  - ./.stacks/vscode
  - ./.stacks
  - ./
