packages:
  - ./.stacks/actions
  - ./.stacks/build
  - ./.stacks/cli
  - ./.stacks/config
  - ./.stacks/css
  - ./.stacks/modules
  - ./.stacks/router
  - ./.stacks/ui
  - ./.stacks/utils
  - ./.stacks/utils/arrays
  - ./.stacks/utils/collections
  - ./.stacks/utils/objects
  - ./.stacks/utils/strings
  - ./.stacks/utils/fs
  - ./.stacks/utils/paths
  - ./.stacks/security
  - ./.stacks/types
  - ./.stacks/vue-components
  - ./.stacks/web-components
  - ./.stacks/functions
  - ./.stacks
  - './apps/**'
  - ./
