packages:
  - ./.stacks/core/actions
  - ./.stacks/core/alias
  - ./.stacks/core/build
  - ./.stacks/core/config
  - ./.stacks/core/helpers
  - ./.stacks/core/modules
  - ./.stacks/core/router
  - ./.stacks/core/ui
  - ./.stacks/core/utils
  - ./.stacks/core/arrays
  - ./.stacks/core/collections
  - ./.stacks/core/objects
  - ./.stacks/core/strings
  - ./.stacks/core/fs
  - ./.stacks/core/paths
  - ./.stacks/core/security
  - ./.stacks/core/types
  - ./.stacks/vue-components
  - ./.stacks/web-components
  - ./.stacks/functions
  - ./.stacks
  - './apps/**'
  - ./
