name: Export Size

on:
  pull_request:
    branches:
      - main

jobs:
  size:
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - uses: antfu/export-size-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }
          paths: .stacks/core/actions,.stacks/core/ai,.stacks/core/alias,.stacks/core/analytics,.stacks/core/arrays,.stacks/core/auth,.stacks/core/buddy,.stacks/core/build,.stacks/core/cache,.stacks/core/cli,.stacks/core/cloud,.stacks/core/collections,.stacks/core/config,.stacks/core/database,.stacks/core/development,.stacks/core/dns,.stacks/core/docs,.stacks/core/email,.stacks/core/error-handling,.stacks/core/events,.stacks/core/git,.stacks/core/health,.stacks/core/logging,.stacks/core/lint,.stacks/core/modules,.stacks/core/notifications,.stacks/core/objects,.stacks/core/orm,.stacks/core/pages,.stacks/core/path,.stacks/core/query-builder,.stacks/core/payments,.stacks/core/push,.stacks/core/realtime,.stacks/core/repl,.stacks/core/router,.stacks/core/scheduler,.stacks/core/search-engine,.stacks/core/security,.stacks/core/server,.stacks/core/signals,.stacks/core/slug,.stacks/core/sms,.stacks/core/storage,.stacks/core/strings,.stacks/core/testing,.stacks/core/tinker,.stacks/core/types,.stacks/core/ui,.stacks/core/utils,.stacks/core/validation,.stacks/core/vite-plugin
          build_script: pnpm --filter .stacks build
