name: Export Size

on:
  pull_request:
    branches:
      - main

jobs:
  size:
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

#      - uses: antfu/export-size-action@v1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          paths: ./storage/framework/stacks/src/actions,./storage/framework/stacks/src/ai,./storage/framework/stacks/src/alias,./storage/framework/stacks/src/analytics,./storage/framework/stacks/src/arrays,./storage/framework/stacks/src/auth,./storage/framework/stacks/src/buddy,./storage/framework/stacks/src/build,./storage/framework/stacks/src/cache,./storage/framework/stacks/src/cli,./storage/framework/stacks/src/cloud,./storage/framework/stacks/src/collections,./storage/framework/stacks/src/config,./storage/framework/stacks/src/database,./storage/framework/stacks/src/development,./storage/framework/stacks/src/dns,./storage/framework/stacks/src/docs,./storage/framework/stacks/src/email,./storage/framework/stacks/src/error-handling,./storage/framework/stacks/src/events,./storage/framework/stacks/src/git,./storage/framework/stacks/src/health,./storage/framework/stacks/src/logging,./storage/framework/stacks/src/lint,./storage/framework/stacks/src/modules,./storage/framework/stacks/src/notifications,./storage/framework/stacks/src/objects,./storage/framework/stacks/src/orm,./storage/framework/stacks/src/pages,./storage/framework/stacks/src/path,./storage/framework/stacks/src/query-builder,./storage/framework/stacks/src/payments,./storage/framework/stacks/src/push,./storage/framework/stacks/src/realtime,./storage/framework/stacks/src/repl,./storage/framework/stacks/src/router,./storage/framework/stacks/src/scheduler,./storage/framework/stacks/src/search-engine,./storage/framework/stacks/src/security,./storage/framework/stacks/src/server,./storage/framework/stacks/src/signals,./storage/framework/stacks/src/slug,./storage/framework/stacks/src/sms,./storage/framework/stacks/src/storage,./storage/framework/stacks/src/strings,./storage/framework/stacks/src/testing,./storage/framework/stacks/src/tinker,./storage/framework/stacks/src/types,./storage/framework/stacks/src/ui,./storage/framework/stacks/src/utils,./storage/framework/stacks/src/validation,./storage/framework/stacks/src/vite-plugin
#          build_script: pnpm --filter=./storage/framework/stacks build
