name: Export Size

on:
  pull_request:
    branches:
      - main

jobs:
  size:
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

#      - uses: antfu/export-size-action@v1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          paths: ./storage/framework/stacks/core/actions,./storage/framework/stacks/core/ai,./storage/framework/stacks/core/alias,./storage/framework/stacks/core/analytics,./storage/framework/stacks/core/arrays,./storage/framework/stacks/core/auth,./storage/framework/stacks/core/buddy,./storage/framework/stacks/core/build,./storage/framework/stacks/core/cache,./storage/framework/stacks/core/cli,./storage/framework/stacks/core/cloud,./storage/framework/stacks/core/collections,./storage/framework/stacks/core/config,./storage/framework/stacks/core/database,./storage/framework/stacks/core/development,./storage/framework/stacks/core/dns,./storage/framework/stacks/core/docs,./storage/framework/stacks/core/email,./storage/framework/stacks/core/error-handling,./storage/framework/stacks/core/events,./storage/framework/stacks/core/git,./storage/framework/stacks/core/health,./storage/framework/stacks/core/logging,./storage/framework/stacks/core/lint,./storage/framework/stacks/core/modules,./storage/framework/stacks/core/notifications,./storage/framework/stacks/core/objects,./storage/framework/stacks/core/orm,./storage/framework/stacks/core/pages,./storage/framework/stacks/core/path,./storage/framework/stacks/core/query-builder,./storage/framework/stacks/core/payments,./storage/framework/stacks/core/push,./storage/framework/stacks/core/realtime,./storage/framework/stacks/core/repl,./storage/framework/stacks/core/router,./storage/framework/stacks/core/scheduler,./storage/framework/stacks/core/search-engine,./storage/framework/stacks/core/security,./storage/framework/stacks/core/server,./storage/framework/stacks/core/signals,./storage/framework/stacks/core/slug,./storage/framework/stacks/core/sms,./storage/framework/stacks/core/storage,./storage/framework/stacks/core/strings,./storage/framework/stacks/core/testing,./storage/framework/stacks/core/tinker,./storage/framework/stacks/core/types,./storage/framework/stacks/core/ui,./storage/framework/stacks/core/utils,./storage/framework/stacks/core/validation,./storage/framework/stacks/core/vite-plugin
#          build_script: pnpm --filter=./storage/framework/stacks build
