name: Homebrew

on:
  release:
    types: [published]

permissions:
  contents: write
  repository-projects: write

jobs:
  update-homebrew:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"

      - name: Setup GitHub CLI
        run: |
          brew install gh
          echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

      - name: Ensure Homebrew Tap Repository Exists
        run: |
          if ! gh repo view stacksjs/homebrew-tap &>/dev/null; then
            gh repo create stacksjs/homebrew-tap --public --description "Homebrew tap for Stacks packages"
          fi

      - name: Update Homebrew Formula
        run: |
          bash .github/scripts/update-homebrew-formula.sh ${{ github.event.release.tag_name }}

      - name: Push to Homebrew Tap Repository
        run: |
          # Clone the tap repo using PAT for authentication
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/stacksjs/homebrew-tap.git

          # Set up Git config
          cd homebrew-tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Copy the formula to the tap repo
          mkdir -p Formula
          cp ../.github/homebrew/stacks.rb Formula/

          # Check if there are changes to commit
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          # Push the changes to the tap repo
          git add Formula/stacks.rb
          git commit -m "Update stacks formula to ${{ github.event.release.tag_name }}"
          git push
