name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Set Application Key
        run: pnpm buddy key:generate

      - name: Prepublish # these packages are required for the "Publish framework" step
        run: pnpm --filter='./.stacks/core/alias' build && pnpm --filter='./.stacks/core/logging' build && pnpm --filter='./.stacks/core/development' build && pnpm --filter='./.stacks/core/utils' build && pnpm --filter='./.stacks/core/storage' build && pnpm --filter='./.stacks/core/path' build && pnpm --filter='./.stacks/core/tinker' build && pnpm --filter='./.stacks/core/**' build

      - name: Publish framework
        run: pnpm --filter './.stacks' --filter './.stacks/core/**' --filter './.stacks/fonts/**' --filter './.stacks/ide/vscode' publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish dummy libraries
        run: pnpm run generate:entries && pnpm --filter './.stacks/libs/components/vue' --filter './.stacks/libs/components/web' --filter './.stacks/libs/functions' publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish VS Code Extension
        run: pnpm --filter './.stacks/ide/vscode' release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Create GitHub release
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
